#!/bin/bash

export PATH=$PATH:/usr/X11/lib/X11/xkb/
dir=`dirname $0`

cd /home/$USER/.config
if [ ! -e config_bepo ]; then
	touch config_bepo && echo '0' > config_bepo
fi

case $(cat config_bepo) in
	'0') echo 1 > config_bepo
	setxkbmap fr bepo_latin9
	notify-send "Disposition BÉPO."
	;;
	'1') echo 0 > config_bepo
	setxkbmap fr-latin9
	notify-send "Disposition AZERTY."
	;;
esac
